"""add_google_calendar_fields_to_medicos

Revision ID: 1abb69329ca5
Revises: a46a341041c2
Create Date: 2025-09-19 20:23:28.109260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abb69329ca5'
down_revision: Union[str, Sequence[str], None] = 'a46a341041c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('google_calendar_token', sa.Text(), nullable=True))
    op.add_column('medicos', sa.Column('calendario_ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicos', 'calendario_ativo')
    op.drop_column('medicos', 'google_calendar_token')
    # ### end Alembic commands ###
